namespace BolsaDeTrabajo.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class CatalogoVariosIII : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO [Sist].[TiposLicencias] VALUES ('A', 'Automovilista / Pasaje y exclusivo de Turismo.')");
            Sql("INSERT INTO [Sist].[TiposLicencias] VALUES ('B', 'Chofer / Carga en sus diferentes modalidades, excepto los materiales y residuos peligrosos.')");
            Sql("INSERT INTO [Sist].[TiposLicencias] VALUES ('C', 'Carga de dos o tres ejes (Torton o Rabón).')");
            Sql("INSERT INTO [Sist].[TiposLicencias] VALUES ('D', 'Chofer - Guía de turista.')");
            Sql("INSERT INTO [Sist].[TiposLicencias] VALUES ('E', 'Carga de materiales y residuos peligrosos.')");
            Sql("INSERT INTO [Sist].[TiposLicencias] VALUES ('F', 'De y hacia los puertos marítimos y aeropuertos federales.')");

            Sql("INSERT INTO [Sist].[TiposDiscapacidades] VALUES ('Auditiva')");
            Sql("INSERT INTO [Sist].[TiposDiscapacidades] VALUES ('Visual')");
            Sql("INSERT INTO [Sist].[TiposDiscapacidades] VALUES ('Intelectual')");
            Sql("INSERT INTO [Sist].[TiposDiscapacidades] VALUES ('Lenguaje')");
            Sql("INSERT INTO [Sist].[TiposDiscapacidades] VALUES ('Motora')");

            Sql("INSERT INTO [Sist].[Idiomas] VALUES ('Aleman')");
            Sql("INSERT INTO [Sist].[Idiomas] VALUES ('Español')");
            Sql("INSERT INTO [Sist].[Idiomas] VALUES ('Frances')");
            Sql("INSERT INTO [Sist].[Idiomas] VALUES ('Ingles')");
            Sql("INSERT INTO [Sist].[Idiomas] VALUES ('Italiano')");
            Sql("INSERT INTO [Sist].[Idiomas] VALUES ('Japones')");
            Sql("INSERT INTO [Sist].[Idiomas] VALUES ('Portugues')");
            Sql("INSERT INTO [Sist].[Idiomas] VALUES ('Ruso')");
            Sql("INSERT INTO [Sist].[Idiomas] VALUES ('Otro')");

            Sql("INSERT INTO [Sist].[Niveles] VALUES ('Muy básico')");
            Sql("INSERT INTO [Sist].[Niveles] VALUES ('Básico')");
            Sql("INSERT INTO [Sist].[Niveles] VALUES ('Intermedio')");
            Sql("INSERT INTO [Sist].[Niveles] VALUES ('Avanzado')");
            Sql("INSERT INTO [Sist].[Niveles] VALUES ('Nativo')");

            Sql("INSERT INTO [Sist].[DocumentosValidadores] VALUES ('Certificado')");
            Sql("INSERT INTO [Sist].[DocumentosValidadores] VALUES ('Cedula Profesional')");
            Sql("INSERT INTO [Sist].[DocumentosValidadores] VALUES ('Carta Pasante')");
            Sql("INSERT INTO [Sist].[DocumentosValidadores] VALUES ('Otro')");

            Sql("SET IDENTITY_INSERT [Sist].[TiposTelefonos] ON");
            Sql("INSERT INTO [Sist].[TiposTelefonos] (Id, Tipo) VALUES (1, 'Móvil')");
            Sql("INSERT INTO [Sist].[TiposTelefonos] (Id, Tipo) VALUES (2, 'Casa')");
            Sql("INSERT INTO [Sist].[TiposTelefonos] (Id, Tipo) VALUES (3, 'Oficina')");
            Sql("SET IDENTITY_INSERT [Sist].[TiposTelefonos] OFF");

            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Acupuntura y medicina oriental')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Administración / administrador de redes y sistemas ')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Administración / gestión de servicios sanitarios')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Administración /administrador de sistemas, redes y comunicaciones LAN/WAN')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Administración /gestión de servicios de hostelería')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Administración /gestión hotelera')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Administración de sistemas informáticos en red ')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Administración publica')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Administración y gestión de empresas, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Administración/gestión de servicios de hostelería')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Alimentación, nutrición y bienestar, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Animación, tecnología interactiva, gráficos en video y efectos especiales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Antropología')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Aprendizaje de una lengua extranjera')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Arquitectura')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Arquitectura naval e ingeniería marítima')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Arte dramático/teatro, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Arte/estudios artísticos, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Artes liberales y ciencias/estudios liberales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Artes plásticas, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Asesoramiento psicológico')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Audiología y trastornos del habla y del lenguaje')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Banca y servicios financieros')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Biblioteconomía')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Biblioteconomía y documentación ')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Bienes inmuebles')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Bioinformática')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Bioingeniería e ingeniería biomédica')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Biología humana')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Biología marina y oceanografía biológica')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Biología molecular')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Biología, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Biología/ciencias biológicas, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Bioquímica')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Bioquímica y biología molecular')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Biotecnología')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Botánica / biología vegetal')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ciencia de materiales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ciencia y gestión de la fauna, las especies marinas y los espacios naturales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ciencias biomédicas, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ciencias de la gestión ')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ciencias de la nutrición')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ciencias físicas')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ciencias físicas')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ciencias medioambientales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ciencias naturales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ciencias políticas y gobierno')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ciencias sociales ')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ciencias vegetales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ciencias veterinarias / ciencias clínicas veterinarias, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ciencias y trastornos de la comunicación, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Cine y video')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Cinematografía y producción de cine y video')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Comercialización ene le ámbito de la moda')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Comunicación empresarial')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Comunicación oral y retorica')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Comunicación organizacional, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Conservación de jardines y céspedes deportivos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Contabilidad')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Contabilidad y finanzas')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Contabilidad y gestión empresarial ')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Derecho')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Derecho financiero y tributario')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Derecho internacional y estudios juridico internacionales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Derecho/jurisprudencia canadiense')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Derecho/jurisprudencia estadounidense ')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Desarrollo de aplicaciones web')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Desarrollo de páginas web, contenido digital /multimedia y recursos informáticos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Desarrollo de recursos humanos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Desarrollo humano y familia, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Desarrollo, planificación y gestión de uso de suelo')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Dirección y administración en el sector educativo, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Diseño de interiores')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Diseño de moda')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Diseño de videojuegos y contenido interactivo')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Diseño grafico')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Diseño industrial y de productos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Diseño y artes aplicadas')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Diseño y comunicación visual, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Economía')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Economía de la empresa')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Educación primaria')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Educación universitaria/gestión en el ámbito de la educación universitaria')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Empresa, gestión, marketing y disciplinas afines')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Empresa/comercio, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Enfermería')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Enfermería de urgencias y emergencias')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Enseñanzas artísticas y artes visuales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Escritura y redacción, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estadística')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios bíblicos/estudios de la biblia')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios de España y Portugal')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios de la zona del pacifico')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios de los medios de comunicación ')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios franceses')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios generales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios japoneses')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios judaicos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios judíos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios jurídicos, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios jurídicos, nivel universitario')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios jurídicos, nivel universitario')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios norteamericanos/civilización norteamericana')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios pastorales /orientación pastoral')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios rusos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios rusos, de Europa central, de Europa del este y de Eurasia')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios sobre comunicación y medios')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios sobre el territorio urbano')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios sobre naturaleza, ocio y tiempo libre ')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios sobre políticas de seguridad nacional')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios ucranianos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios uraloaltaicos y del centro asiático')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios zonales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Estudios zonales, étnicos, culturales y de grupos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Farmacia')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Farmacología')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Filosofía')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Finanzas, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Física')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Física nuclear')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Física química')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Física teórica y matemática')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Fisioterapia/fisioterapeuta')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Fotografía')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Geografía')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Geología/ciencias de la tierra, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión de centros universitarios técnicos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión de empresas/organizaciones sin ánimo de lucro/entidades publicas')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión de la construcción')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión de los recursos naturales y políticas afines')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión de proyectos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión de proyectos de tecnología de la información')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión de recursos de la información')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión de recursos humanos/administración de personal, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión de servicios turísticos y de viaje')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión de situaciones de crisis /urgencias / desastre')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión del agua, las zonas húmedas y los recursos marinos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión forestal en el medio urbano')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión industrial/de ingeniería')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión logística, de materiales y de la cadena de suministros')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión y servicios de recursos humanos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión y supervisión de oficinas')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Gestión y supervisión de operaciones')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Hidrología y gestión de recursos hídricos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Higienista dental')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Historia')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Historia de los estados unidos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Historia del arte, crítica de arte y conservación del patrimonio artístico.')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Historia y arqueología del mundo clásico, mediterráneo antiguo y oriente próximo')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Humanidades/estudios humanísticos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Informática, comunicaciones y servicios de asistencia')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería aeroespacial, aeronáutica y astronáutica')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería agrónoma y producción vegetal')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería biomédica/medica')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería civil')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería de materiales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería de software')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería de telecomunicaciones')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería eléctrica y electrónica')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería eléctrica, electrónica y de comunicaciones ')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería física')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería física/física aplicada')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería industrial')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería informática')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería mecánica ')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería medioambiental / ingeniería de salud medioambiental')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería nuclear')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería química')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ingeniería química y biomolecular')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Interacción entre el ser humano y la tecnología')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Inversiones y títulos valores')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Investigación de operaciones /operativa')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Jazz/estudios de jazz')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Justicia penal y servicios correccionales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Justicia penal/gestión de la aplicación de la ley')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Justicia penal/Policía')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Justicia penal/seguridad')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Kinesiología/quinesiología y ciencia del ejercicio')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Kinesioterapia/kinesioterapeuta')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Lengua y literatura inglesa')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Lengua y literatura inglesa, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Lengua y literatura japonesa')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Lengua y literatura ucraniana')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Lengua y literatura urdu')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Liderazgo empresarial')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Lingüística')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Literatura infantil y juvenil')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Literatura inglesa (británica)')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Marketing')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Marketing / gestión de marketing, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Matemáticas')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Matemáticas aplicadas')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Matemáticas e informática')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Mecánica y reparación, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Medicina')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Medicina naturista/medicina natural/naturopatía')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Medicina quiropráctica')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Microbiología, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Música')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Náutica/ingeniería marítima')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Negocios internacionales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Negocios internacionales /comercio internacional')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Neurobiología y conducta')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Neurociencia')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Nutrición humana')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Oceanografía, química y física')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Odontología')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Operaciones y ciencias militares')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Óptica y optometría')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Optometría')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ordenación del territorio, urbanismo y medio ambiente')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Orientación /orientación de rehabilitación profesional')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Orientación de alumnos de primaria y secundaria')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Orientación de alumnos universitario')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Orientación pastoral para la juventud')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Orientación pastoral para la vida urbana')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Patología vegetal / fitopatología')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Pedagogía waldorf')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Periodismo')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Planificación urbana y regional')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Planificación y servicios financieros')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Política y gobierno de estados unidos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Preservación y conservación del patrimonio histórico')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Procuraduría')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Profesiones y estudios jurídicos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Programación informática')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Programación informática, aplicaciones especificas')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Psicología')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Psicología clínica')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Psicología del trabajo')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Publicidad')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Química')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Química ambiental')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Química analítica')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Química aplicada a la ingeniería')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Química de materiales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Química de polímeros')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Química física')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Química inorgánica')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Química medica y farmacéutica')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Química orgánica')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Radio y televisión')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Recursos naturales/conservación, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Relaciones internacionales y asuntos exteriores')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Relaciones laborales industriales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Relaciones publicas /gestión de imagen')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Religión / estudios religiosos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Residencia en medicina de urgencias')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Residencia en medicina zoológica')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Retórica y composición')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Salud y bienestar, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Salud y educación física')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Secretariado judicial')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Servicios financieros y gestión financiera')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Servicios humanos, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Servicios sanitarios / ciencias de la salud, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Sistema tributario')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Sistemas de información de gestión, general')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Sociología')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Teatro')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Técnico de laboratorio clínico/medico')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Técnico en salud animal / auxiliar de veterinaria')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Técnico quirúrgico')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Tecnología / técnico de ingeniería eléctrica, electrónica y de comunicaciones')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Tecnología / técnico de ingeniería química ')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Tecnología / técnico industrial')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Tecnología de la educación')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Tecnología de la información ')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Tecnología de procesos químicos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Tecnología en la educación')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Tecnología informática / tecnología de sistemas informáticos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Tecnología química / Técnico químico')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Tecnologías relacionadas con la ingeniería mecánica')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Teología/estudios teológicos')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Terapia mediante masaje / masaje terapéutico')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Terapia ocupacional')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Trabajo social')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Transcripción de juicios/taquigrafía judicial')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Trastornos del habla y del lenguaje')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ventas especializadas, promoción comercial y actividades de marketing')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Ventas generales, promoción comercial y actividades de marketing afines')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Veterinaria')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Viajes y exploración')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Virología')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Voz y opera')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Zoo terapia / terapia asistida con animales')");
            Sql("INSERT INTO [Sist].[Carreras] (carrera) VALUES ('Zoología /biología animal')");
        }
        
        public override void Down()
        {
        }
    }
}
